character_set_sprite("body_keia00", spr_layer_type.body);
character_set_sprite("jacket_keia00", spr_layer_type.jacket);
character_set_sprite("shoes_keia00", spr_layer_type.shoes);
character_set_sprite("tshirt_keia00", spr_layer_type.tshirt);
character_set_sprite("trousers_keia00", spr_layer_type.trousers);
character_set_sprite("hairback_keia00", spr_layer_type.hairback);
character_set_sprite("hairfront_keia00", spr_layer_type.hairfront);
character_set_sprite("makeup_keia00", spr_layer_type.makeup);
character_set_sprite("face_keia00", spr_layer_type.face);
